// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlsh25BBA2emS5-gQxzFYBGgwm3FgtJxA',
    appId: '1:339701683930:web:96a4cf82b07799a3b0b7e3',
    messagingSenderId: '339701683930',
    projectId: 'gearcare-4c0d9',
    authDomain: 'gearcare-4c0d9.firebaseapp.com',
    storageBucket: 'gearcare-4c0d9.appspot.com',
    measurementId: 'G-7PMMK621N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZyWyW2c627ZaRPM30hkv8sd5CVRTpCg',
    appId: '1:339701683930:android:c33f8d2efba5adfdb0b7e3',
    messagingSenderId: '339701683930',
    projectId: 'gearcare-4c0d9',
    storageBucket: 'gearcare-4c0d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAf7Fm-gyWm_9Qi6Q6d0UGdlL8dN2pU4',
    appId: '1:339701683930:ios:fd2929401b241d13b0b7e3',
    messagingSenderId: '339701683930',
    projectId: 'gearcare-4c0d9',
    storageBucket: 'gearcare-4c0d9.appspot.com',
    iosBundleId: 'com.example.gearCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByAf7Fm-gyWm_9Qi6Q6d0UGdlL8dN2pU4',
    appId: '1:339701683930:ios:dd8009f179c8ae82b0b7e3',
    messagingSenderId: '339701683930',
    projectId: 'gearcare-4c0d9',
    storageBucket: 'gearcare-4c0d9.appspot.com',
    iosBundleId: 'com.example.gearCare.RunnerTests',
  );
}
